# Generated by Django 2.1.1 on 2018-10-21 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('appr', models.BooleanField(default=False)),
                ('op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('typ', models.CharField(choices=[('a', 'Quiz'), ('b', 'Mid-Semester Exam'), ('c', 'End-Semester Exam'), ('d', 'Assignment'), ('e', 'Notes'), ('f', 'Slides'), ('g', 'Textbook')], default='a', max_length=3, verbose_name='Type')),
                ('num', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Number')),
                ('fl', models.FileField(upload_to='', verbose_name='File')),
                ('appr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Itr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('FA', 'fall'), ('SP', 'spring'), ('SU', 'summer'), ('WI', 'winter')], default='FA', max_length=1, verbose_name='Semester')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('inst', models.CharField(max_length=32, verbose_name='Instructor')),
                ('appr', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('op', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=64, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(max_length=2048, null=True)),
                ('appr', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=256)),
                ('appr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Item')),
            ],
            bases=('main.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='itr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Itr'),
        ),
        migrations.AddField(
            model_name='item',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
        migrations.AddField(
            model_name='solitem',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Item'),
        ),
    ]
