# Generated by Django 2.1.1 on 2018-12-26 10:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fl',
            field=models.FileField(upload_to=main.models.gen_file_name, verbose_name='File'),
        ),
    ]
