# Generated by Django 2.1.1 on 2018-10-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('vis', models.BooleanField(default=False)),
                ('itr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Itr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='log',
            old_name='joined',
            new_name='ts',
        ),
    ]
