# Generated by Django 2.1.1 on 2018-12-28 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20181226_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='info',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='time',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemreport',
            name='info',
        ),
        migrations.RemoveField(
            model_name='itemreport',
            name='time',
        ),
        migrations.RemoveField(
            model_name='itemreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='info',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='time',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='user',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='report_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreport',
            name='report_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Report'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='report_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Report'),
            preserve_default=False,
        ),
    ]
