# Generated by Django 2.1.1 on 2018-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181021_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='itr',
            name='sem',
            field=models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer'), ('WI', 'Winter')], default='FA', max_length=1, verbose_name='Semester'),
        ),
    ]
