# Generated by Django 2.1.1 on 2019-01-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181228_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='info',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='typ',
            field=models.CharField(choices=[('ab', 'Abusive'), ('ma', 'Malicious'), ('ot', 'Off-Topic'), ('sp', 'Spam'), ('oh', 'Other')], default=None, max_length=2, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreport',
            name='typ',
            field=models.CharField(choices=[('ma', 'Malicious'), ('ur', 'Unrelated'), ('du', 'Duplicate'), ('sp', 'Spam'), ('oh', 'Other')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='typ',
            field=models.CharField(choices=[('ab', 'Abusive'), ('im', 'Imposter'), ('oh', 'Other')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
