# Generated by Django 2.1.1 on 2018-12-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_commentreport_itemreport_userreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='vis',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
