# Generated by Django 2.1.1 on 2018-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181222_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='num',
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
