# Generated by Django 2.1.1 on 2018-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
